nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://%env(DOMAIN)%']
        allow_headers: ['Content-Type', 'authorization']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
