image: docker:latest

services:
- docker:dind

stages:
- build
- test

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/app
  APP_IMAGE_WITH_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/app:$CI_COMMIT_SHA
  NGINX_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/nginx
  NGINX_IMAGE_WITH_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/nginx:$CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t ${APP_IMAGE_WITH_TAG} -f Dockerfile-php .
    - docker build --pull -t ${NGINX_IMAGE_WITH_TAG} ./docker/nginx
    - docker push ${APP_IMAGE_WITH_TAG}
    - docker push ${NGINX_IMAGE_WITH_TAG}
    - docker tag ${APP_IMAGE_WITH_TAG} ${APP_IMAGE}:latest
    - docker tag ${NGINX_IMAGE_WITH_TAG} ${NGINX_IMAGE}:latest
    - docker push ${APP_IMAGE}:latest
    - docker push ${NGINX_IMAGE}:latest

test1:
  stage: test
  script:
    - docker pull $APP_IMAGE_WITH_TAG
    - docker run -w /var/www -e APP_ENV=test $APP_IMAGE_WITH_TAG vendor/bin/phpunit
