pipelines:
  tags:
    '*':
      - step:
          services:
            - docker
          script:
            - echo $GCR_KEY | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
            - export IMAGE_NAME=eu.gcr.io/the-dots/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
