version: "3"
services:
  nginx:
    build: ./docker/nginx
    links:
      - php
    ports:
      - "80:80"
      - "443:443"

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ".:/var/www:rw,cached"
