home:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::homeAction' }
    methods:  [GET]

index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }
    methods:  [POST]

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
